[package]
name = "unique-ipv4-counter-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
num_cpus = "1.16.0"
memmap = "0.7.0"
rand = "0.8.5"

[profile.release]
panic = "abort"
overflow-checks = false
opt-level = 3
debug = "full"


