[build]
rustflags = [
    "-Ctarget-feature=+avx2",
    "-Ctarget-cpu=native",
#    "-Cprofile-generate=/tmp/pgo-data",
# ~/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/bin/llvm-profdata \
#    merge -o /tmp/pgo-data/merged.profdata /tmp/pgo-data
#    "-Cprofile-use=/tmp/pgo-data/merged.profdata",
#    "-Cllvm-args=-pgo-warn-missing-function",
]
